name: WebDAV Sync

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight (UTC)
  workflow_dispatch:  # Allows manual triggering if needed

jobs:
  sync_job:
    runs-on: ubuntu-latest

    env:
      WEBDAV_HOSTNAME: ${{ secrets.WEBDAV_HOSTNAME }}
      WEBDAV_LOGIN: ${{ secrets.WEBDAV_LOGIN }}
      WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}
      DATABASE_ID: ${{ secrets.DATABASE_ID }}
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install webdavclient3 python-dateutil pillow matplotlib numpy requests

      - name: Run sync script and save output to log
        env:
          WEBDAV_HOSTNAME: ${{ env.WEBDAV_HOSTNAME }}
          WEBDAV_LOGIN: ${{ env.WEBDAV_LOGIN }}
          WEBDAV_PASSWORD: ${{ env.WEBDAV_PASSWORD }}
          DATABASE_ID: ${{ env.DATABASE_ID }}
          NOTION_TOKEN: ${{ env.NOTION_TOKEN }}
        run: |
          python action-webdav.py